Collections:
  - Name: SSN
    Metadata:
      Training Techniques:
        - AdamW
      Training Resources: 8x GeForce GTX 1080 Ti
      Architecture:
        - Hard Voxelization
    Paper:
      URL: https://arxiv.org/abs/2004.02774
      Title: 'SSN: Shape Signature Networks for Multi-class Object Detection from Point Clouds'
    README: configs/ssn/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/dense_heads/shape_aware_head.py#L166
      Version: v0.7.0

Models:
  - Name: hv_ssn_secfpn_sbn-all_2x16_2x_nus-3d
    In Collection: SSN
    Config: configs/ssn/hv_ssn_secfpn_sbn-all_2x16_2x_nus-3d.py
    Metadata:
      Training Data: nuScenes
      Training Memory (GB): 3.6
    Results:
      - Task: 3D Object Detection
        Dataset: nuScenes
        Metrics:
          mAP: 40.91
          NDS: 54.44
    Weights: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/ssn/hv_ssn_secfpn_sbn-all_2x16_2x_nus-3d/hv_ssn_secfpn_sbn-all_2x16_2x_nus-3d_20210830_101351-51915986.pth

  - Name: hv_ssn_regnet-400mf_secfpn_sbn-all_2x16_2x_nus-3d
    In Collection: SSN
    Config: configs/ssn/hv_ssn_regnet-400mf_secfpn_sbn-all_2x16_2x_nus-3d.py
    Metadata:
      Training Data: nuScenes
      Training Memory (GB): 5.1
    Results:
      - Task: 3D Object Detection
        Dataset: nuScenes
        Metrics:
          mAP: 46.65
          NDS: 58.24
    Weights: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/ssn/hv_ssn_regnet-400mf_secfpn_sbn-all_2x16_2x_nus-3d/hv_ssn_regnet-400mf_secfpn_sbn-all_2x16_2x_nus-3d_20210829_210615-361e5e04.pth

  - Name: hv_ssn_secfpn_sbn-all_2x16_2x_lyft-3d
    In Collection: SSN
    Config: configs/ssn/hv_ssn_secfpn_sbn-all_2x16_2x_lyft-3d.py
    Metadata:
      Training Data: Lyft
      Training Memory (GB): 8.5
    Results:
      - Task: 3D Object Detection
        Dataset: Lyft
        Metrics:
          Private Score: 17.5
          Public Score: 17.5
    Weights: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/ssn/hv_ssn_secfpn_sbn-all_2x16_2x_lyft-3d/hv_ssn_secfpn_sbn-all_2x16_2x_lyft-3d_20210822_134731-46841b41.pth

  - Name: hv_ssn_regnet-400mf_secfpn_sbn-all_1x16_2x_lyft-3d
    In Collection: SSN
    Config: configs/ssn/hv_ssn_regnet-400mf_secfpn_sbn-all_1x16_2x_lyft-3d.py
    Metadata:
      Training Data: Lyft
      Training Memory (GB): 7.4
    Results:
      - Task: 3D Object Detection
        Dataset: Lyft
        Metrics:
          Private Score: 17.9
          Public Score: 18.0
    Weights: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/ssn/hv_ssn_regnet-400mf_secfpn_sbn-all_1x16_2x_lyft-3d/hv_ssn_regnet-400mf_secfpn_sbn-all_1x16_2x_lyft-3d_20210829_122825-d93475a1.pth
