Collections:
  - Name: MVX-Net
    Metadata:
      Training Data: KITTI
      Training Techniques:
        - AdamW
      Training Resources: 8x V100 GPUs
      Architecture:
        - Feature Pyramid Network
        - Dynamic Voxelization
    Paper: https://arxiv.org/abs/1904.01649
    README: configs/mvxnet/README.md

Models:
  - Name: dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class
    In Collection: MVX-Net
    Config: configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py
    Metadata:
      Training Memory (GB): 6.7
    Results:
      - Task: 3D Object Detection
        Dataset: KITTI
        Metrics:
          mAP: 63.0
    Weights: https://download.openmmlab.com/mmdetection3d/v0.1.0_models/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class_20200621_003904-10140f2d.pth
