Collections:
  - Name: SPVCNN
    Metadata:
      Training Techniques:
        - AdamW
      Architecture:
        - SPVCNN
    Paper:
      URL: https://arxiv.org/abs/2007.16100
      Title: 'Searching Efficient 3D Architectures with Sparse Point-Voxel Convolution'
    README: configs/spvcnn/README.md
    Code:
      URL:
      Version: v1.1.0rc3

Models:
  - Name: spvcnn_w16_8xb2-15e_semantickitti
    In Collection: SPVCNN
    Config: configs/spvcnn/spvcnn_w16_8xb2-15e_semantickitti.py
    Metadata:
      Training Data: SemanticKITTI
      Training Memory (GB): 3.9
      Training Resources: 8x A100 GPUs
    Results:
      - Task: 3D Semantic Segmentation
        Dataset: SemanticKITTI
        Metrics:
          mIOU: 61.7
    Weights:

  - Name: spvcnn_w20_8xb2-15e_semantickitti
    In Collection: SPVCNN
    Config: configs/spvcnn/spvcnn_w20_8xb2-15e_semantickitti.py
    Metadata:
      Training Data: SemanticKITTI
      Training Memory (GB): 4.2
      Training Resources: 8x A100 GPUs
    Results:
      - Task: 3D Semantic Segmentation
        Dataset: SemanticKITTI
        Metrics:
          mIOU: 62.9
    Weights:

  - Name: spvcnn_w32_8xb2-15e_semantickitti
    In Collection: SPVCNN
    Config: configs/spvcnn/spvcnn_w32_8xb2-15e_semantickitti.py
    Metadata:
      Training Data: SemanticKITTI
      Training Memory (GB): 5.4
      Training Resources: 8x A100 GPUs
    Results:
      - Task: 3D Semantic Segmentation
        Dataset: SemanticKITTI
        Metrics:
          mIOU: 63.4
    Weights:
